### ISSUE TITLE
Convert cats.js to json

### ISSUE THREAD

**Issue by piranna** [coleww/cat-me#2]
This would make it cleaner, and also easier to reuse and extend :-) I propose to define the cats drawing as an array of strings and later join them in runtime.

**Comment by coleww** [comment]
good call! i have no idea what i was thinking writing cats.js in that way :| 

if you want to make a PR that does that I would certainly merge it :D

**Comment by piranna** [comment]
> if you want to make a PR that does that I would certainly merge it :D

[Done](https://github.com/coleww/cat-me/pull/3) ;-) I've seen some of the cats has spaces on the left side, I think they could be trimmed, what do you think? Also `grumpy` has a background, I think it should be changed for spaces too...

**Comment by coleww** [comment]
sure yeah, i would merge both those things as well! :cat:

**Comment by piranna** [comment]
> sure yeah, i would merge both those things as well!

[Done](https://github.com/coleww/cat-me/pull/4) :smile_cat:
